-- ================================================================
-- ESQUEMA INTEGRAL UNIFICADO PARA FARMACIA VANNESA EN SUPABASE
-- Este script crea todas las tablas, relaciones, índices y políticas
-- para la operación en la nube (PostgreSQL / Supabase).
-- Copia y ejecuta este script en el SQL Editor de tu Dashboard de Supabase.
-- ================================================================

-- 1. TABLA DE USUARIOS (users)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'cajero',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. TABLA DE CLIENTES (clients)
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    identity_card VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA DE MEDICAMENTOS Y PRODUCTOS (products)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    generic_name VARCHAR(150) NOT NULL,
    product_code VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    stock INTEGER NOT NULL DEFAULT 0,
    presentation VARCHAR(100) NOT NULL,
    laboratory VARCHAR(100) NOT NULL,
    expiration_date VARCHAR(50) NOT NULL,
    dose VARCHAR(50) NOT NULL,
    cost_price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    sale_price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. TABLA DE VENTAS (sales)
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. TABLA DE DETALLES DE VENTA (sale_items)
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL
);

-- 6. TABLA DE BITÁCORA DE AUDITORÍA TI (audit_logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    action VARCHAR(255) NOT NULL,
    details TEXT,
    timestamp VARCHAR(50) NOT NULL DEFAULT to_char(timezone('utc'::text, now()), 'YYYY-MM-DD HH24:MI:SS')
);

-- 7. TABLA DE TURNOS Y APERTURA/CIERRE DE CAJA (cash_shifts)
CREATE TABLE IF NOT EXISTS public.cash_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    shift_name VARCHAR(50) NOT NULL DEFAULT 'Matutino',
    register_name VARCHAR(50) NOT NULL DEFAULT 'Caja #1 - Principal',
    initial_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    expected_cash NUMERIC(12, 2) DEFAULT NULL,
    physical_cash NUMERIC(12, 2) DEFAULT NULL,
    difference NUMERIC(12, 2) DEFAULT NULL,
    vault_deposit NUMERIC(12, 2) DEFAULT NULL,
    remnant_cash NUMERIC(12, 2) DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Abierta', -- 'Abierta', 'Cerrada'
    notes TEXT,
    opened_at VARCHAR(50) NOT NULL,
    closed_at VARCHAR(50) DEFAULT NULL
);

-- 8. TABLA DE MOVIMIENTOS DETALLADOS DE CAJA (cash_movements)
CREATE TABLE IF NOT EXISTS public.cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT REFERENCES public.cash_shifts(id) ON DELETE SET NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    movement_type VARCHAR(30) NOT NULL, -- 'Ingreso', 'Egreso', 'Retiro Bóveda'
    category VARCHAR(60) NOT NULL DEFAULT 'Operativo',
    concept VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    voucher_reference VARCHAR(50) DEFAULT NULL,
    created_at VARCHAR(50) NOT NULL
);

-- 9. TABLA DE MOVIMIENTOS Y KARDEX DE INVENTARIO (inventory_movements)
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    movement_type VARCHAR(30) NOT NULL, -- 'Entrada', 'Salida', 'Ajuste / Merma'
    quantity INTEGER NOT NULL,
    previous_stock INTEGER NOT NULL DEFAULT 0,
    new_stock INTEGER NOT NULL DEFAULT 0,
    reason VARCHAR(100) NOT NULL,
    notes TEXT,
    created_at VARCHAR(50) NOT NULL
);

-- ÍNDICES PARA ALTO RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_products_code ON public.products(product_code);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);
CREATE INDEX IF NOT EXISTS idx_clients_identity ON public.clients(identity_card);
CREATE INDEX IF NOT EXISTS idx_sales_date ON public.sales(date DESC);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON public.sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_cash_shifts_status ON public.cash_shifts(status);
CREATE INDEX IF NOT EXISTS idx_cash_movements_shift ON public.cash_movements(shift_id);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product ON public.inventory_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON public.audit_logs(timestamp DESC);

-- HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS DE ACCESO
CREATE POLICY "Permitir todo en users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en products" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en sales" ON public.sales FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en sale_items" ON public.sale_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en cash_shifts" ON public.cash_shifts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en cash_movements" ON public.cash_movements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en inventory_movements" ON public.inventory_movements FOR ALL USING (true) WITH CHECK (true);

-- ================================================================
-- FIN DEL ESQUEMA INTEGRAL
-- ================================================================
