-- ================================================================
-- ESQUEMA COMPLETO PARA FARMACIA VANNESA EN SUPABASE
-- Proyecto: zxzijpdexookreuwymbp
-- Copia y pega este contenido en el SQL Editor de tu Dashboard de Supabase:
-- https://supabase.com/dashboard/project/zxzijpdexookreuwymbp/sql/new
-- ================================================================

-- 1. TABLA: TURNOS Y APERTURA/CIERRE DE CAJA (cash_shifts)
CREATE TABLE IF NOT EXISTS public.cash_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    shift_name VARCHAR(50) NOT NULL DEFAULT 'Matutino',
    register_name VARCHAR(50) NOT NULL DEFAULT 'Caja #1 - Principal',
    initial_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    expected_cash NUMERIC(12, 2) DEFAULT NULL,
    physical_cash NUMERIC(12, 2) DEFAULT NULL,
    difference NUMERIC(12, 2) DEFAULT NULL,
    vault_deposit NUMERIC(12, 2) DEFAULT NULL,
    remnant_cash NUMERIC(12, 2) DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Abierta', -- 'Abierta', 'Cerrada'
    notes TEXT,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    closed_at TIMESTAMPTZ DEFAULT NULL
);

-- 2. TABLA: MOVIMIENTOS DETALLADOS DE CAJA (cash_movements)
CREATE TABLE IF NOT EXISTS public.cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT REFERENCES public.cash_shifts(id) ON DELETE SET NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    movement_type VARCHAR(30) NOT NULL, -- 'Ingreso', 'Egreso', 'Retiro Bóveda'
    category VARCHAR(60) NOT NULL DEFAULT 'Operativo',
    concept VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    voucher_reference VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA: MOVIMIENTOS Y KARDEX DE INVENTARIO (inventory_movements)
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    movement_type VARCHAR(30) NOT NULL, -- 'Entrada', 'Salida', 'Ajuste / Merma'
    quantity INTEGER NOT NULL,
    previous_stock INTEGER NOT NULL DEFAULT 0,
    new_stock INTEGER NOT NULL DEFAULT 0,
    reason VARCHAR(100) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. HABILITAR ROW LEVEL SECURITY (RLS) CON ACCESO COMPLETO PARA EL SISTEMA
ALTER TABLE public.cash_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo en cash_shifts" ON public.cash_shifts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en cash_movements" ON public.cash_movements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en inventory_movements" ON public.inventory_movements FOR ALL USING (true) WITH CHECK (true);

-- 5. ÍNDICES PARA CONSULTAS RÁPIDAS
CREATE INDEX IF NOT EXISTS idx_cash_shifts_status ON public.cash_shifts(status);
CREATE INDEX IF NOT EXISTS idx_cash_movements_shift ON public.cash_movements(shift_id);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product ON public.inventory_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_created ON public.inventory_movements(created_at DESC);

-- 6. RESTRICCIONES DE VALIDACIÓN (CONSTRAINTS) EN BD
-- A) Código de producto único e irrepetible
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_product_code') THEN
        ALTER TABLE public.products ADD CONSTRAINT unique_product_code UNIQUE (product_code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'check_quantity_positive') THEN
        ALTER TABLE public.sale_items ADD CONSTRAINT check_quantity_positive CHECK (quantity > 0);
    END IF;
END $$;

-- ================================================================
-- FIN DEL SCRIPT. Ejecuta con el botón verde 'RUN' en Supabase.
-- ================================================================

